# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD$

PORTNAME=	mm-common
PORTVERSION=	0.9.10
CATEGORIES=	devel gnome
MASTER_SITES=	GNOME

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Common build infrastructure for the GNOME C++ binding libraries

LIB_DEPENDS=	libcurl.so:ftp/curl

USES=		gmake pathfix tar:xz
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
