--- config/elasticsearch.yml.orig	2018-02-16 16:43:35 UTC
+++ config/elasticsearch.yml
@@ -31,10 +31,15 @@
 # Path to directory where to store the data (separate multiple locations by comma):
 #
 #path.data: /path/to/data
+path.data: /var/db/elasticsearch
 #
 # Path to log files:
 #
 #path.logs: /path/to/logs
+path.logs: /var/log/elasticsearch
+#
+# Path to scripts dir:
+path.scripts: /usr/local/libexec/elasticsearch
 #
 # ----------------------------------- Memory -----------------------------------
 #
@@ -86,3 +91,6 @@
 # Require explicit names when deleting indices:
 #
 #action.destructive_requires_name: true
+
+# Required on non-Linux platforms
+bootstrap.system_call_filter: false
