# Created by: Jean-Yves Lefort <jylefort@FreeBSD.org>
# $FreeBSD$

PORTREVISION=	1

NO_ARCH=	yes
REFERENCE_SRC=	${WRKSRC}/docs

.include "${.CURDIR}/../../devel/glib20-reference/bsd.gnome-reference.mk"
