--- kak-lsp.toml.orig	2019-01-14 07:08:28 UTC
+++ kak-lsp.toml
@@ -52,11 +52,22 @@ filetypes = ["python"]
 roots = ["requirements.txt", "setup.py", ".git", ".hg"]
 command = "pyls"
 
+#[language.c_cpp]
+#filetypes = ["c", "cpp"]
+#roots = ["compile_commands.json", ".cquery"]
+#command = "cquery"
+#args = ["--init={\"cacheDirectory\":\"/tmp/cquery\",\"highlight\":{\"enabled\":true}}"]
+
 [language.c_cpp]
 filetypes = ["c", "cpp"]
-roots = ["compile_commands.json", ".cquery"]
-command = "cquery"
-args = ["--init={\"cacheDirectory\":\"/tmp/cquery\",\"highlight\":{\"enabled\":true}}"]
+roots = ["compile_commands.json", ".ccls", ".git"]
+command = "ccls"
+# With completion.detailedLabel turned on ccls embeds type
+# signatures and other metadata in completion entries.  Kak-lsp
+# does not filter them, so they appear alongside the selected entry,
+# which is not very convenient.  It is recommended that you disable
+# it.
+args = ["--init={\"completion\":{\"detailedLabel\":false}}"]
 
 [language.haskell]
 filetypes = ["haskell"]
@@ -64,11 +75,17 @@ roots = ["Setup.hs", "stack.yaml", "*.cabal"]
 command = "hie"
 args = ["--lsp"]
 
+#[language.go]
+#filetypes = ["go"]
+#roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
+#command = "go-langserver"
+#args = ["-mode", "stdio", "-gocodecompletion"]
+
 [language.go]
 filetypes = ["go"]
 roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
-command = "go-langserver"
-args = ["-mode", "stdio", "-gocodecompletion"]
+command = "bingo"
+args = ["-mode", "stdio"]
 
 [language.bash]
 filetypes = ["sh"]
