# $FreeBSD$

PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
PKGNAMESUFFIX=	1

COMMENT=	Python3 bindings for GStreamer 1.x

SLAVE_PORT=	python3

MASTERDIR=	${.CURDIR}/../../multimedia/pygstreamer1-common
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
