# $FreeBSD$

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	GStreamer kms video output plugin

GST_PLUGIN=	kms
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
