# Created by: Joe Marcus Clarke <marcus@FreeBSD.org>
# $FreeBSD$

PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
PKGNAMESUFFIX=	3

COMMENT=	Python bindings for GObject for ${PY_FLAVOR}

SLAVE_PORT=	python

MASTERDIR=	${.CURDIR}/../../devel/pygobject3-common
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
