# Created by: ijliao
# $FreeBSD$

PORTNAME=	fribidi
PORTVERSION=	1.0.9
CATEGORIES=	converters
MASTER_SITES=	https://github.com/fribidi/fribidi/releases/download/v${PORTVERSION}/

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Free Implementation of the Unicode Bidirectional Algorithm

LICENSE=	LGPL21
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		meson pathfix tar:xz
USE_LDCONFIG=	yes

.include <bsd.port.mk>
