# $FreeBSD$

PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
PKGNAMESUFFIX=	1

COMMENT=	Python2 bindings for GStreamer 1.x

SLAVE_PORT=	python2

MASTERDIR=	${.CURDIR}/../../multimedia/pygstreamer1-common
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
