# $FreeBSD$

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	GStreamer webrtcdsp plugin

GST_PLUGIN=	webrtcdsp
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
