# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD$

PORTNAME=	gnome-video-effects
PORTVERSION=	0.5.0
CATEGORIES=	graphics
MASTER_SITES=	GNOME

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Collection of Gstreamer effects

USE_GNOME=	intltool
USES=		gettext gnome meson pathfix tar:xz
NO_ARCH=	yes

.include <bsd.port.mk>
