# $FreeBSD$

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	GStreamer CDDA extraction (aka audio ripping) plugin

GST_PLUGIN=	cdparanoia
DIST=		base

BROKEN=		needs newer cdparanoia

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
